### ISSUE TITLE
Vercel sponsorship Criteria

### ISSUE THREAD

**Issue by azu** [azu/philan.net#51]
Currently, we have used vercel as a platform.
Details: <https://efcl.info/2021/03/10/philan.net/>

- [Can Vercel sponsor my open source project? - Vercel Support Article](https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project)

Vercel support open source project.
We want to get this sponsorship program.

## Check list

- [x] The project should be non-commercial.
- [x] The project should be open source.
- [x] The project should be static rather than server-rendered.
- [x] The project should not be related in any way to cryptocurrency.
- [x] A Vercel banner in the footer of each site page.
- [x] A Vercel banner in the source repository's README.md file.
- [x] All links back to Vercel should use a UTM tag with the format: `?utm_source=[team-name]&utm_campaign=oss`

## TODO

- [ ] Send  e-mail to vercel
- [ ] Confirm the response

**Comment by azu** [comment]
close by #53 

Vercel open source diallow to use Next.js's ISR and SSR.
